# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers_api', '0002_auto_20180917_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='status_text',
            new_name='blog_post',
        ),
    ]
