# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers_api', '0003_auto_20180918_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='blog_post',
            new_name='status_text',
        ),
    ]
